# Generated by Django 4.2.5 on 2023-10-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='c_date_date',
            new_name='c_date',
        ),
    ]
